# This is a basic workflow to help you get started with auto deployment

name: Personal-Brand-Wokflow
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          
      - name: Build-and-deploy
        run: |
          hugo
          git remote set-url origin https://sheenamnarula:sharewithall1@github.com/sheenamnarula/generic-workflow.git         
          git config --global user.name "sheenamnarula"
          git config --global user.email sheenamnarula1993@gmail.com
          git checkout -b test-branch    
          git add sheenamnarula1993.github.io/
          git commit -m"changes published to github page"
          git remote -v
          git push origin test-branch

